export const DIRECT: 0;
export const OBJECT: number;
export const ARRAY: number;
export const FUNCTION: number;
export const SYMBOL: number;
export const REMOTE: number;
export const REMOTE_OBJECT: number;
export const REMOTE_ARRAY: number;
export const REMOTE_FUNCTION: number;
